from tkinter import *                 #ABHISHEK
from datetime import *
from PIL import ImageTk
import tkinter.messagebox
from tkcalendar import *
from foodmenus import *
from dateutil import parser

#===============================================defining curerent time and date======================#ABHIHSHEK===================
now = datetime.now()
current_time = now.time().strftime("%H")
current_day = now.strftime("%A")
#===============================================defining all frames===================================#ABHISHEK==================                           
window=Tk()
window.resizable(0,0)
window.geometry("500x750")

mainframe=Frame(window)
mainframe.grid(row=0, column=0, sticky='news')
photo1 = ImageTk.PhotoImage(file = "image6.jpeg") # label used for getting the image as the background image
w1 = Label(mainframe,image = photo1)
w1.pack() # used to pack the picture within the frame 

user_defined=Frame(window)
user_defined.grid(row=0, column=0, sticky='news')
photo2 = ImageTk.PhotoImage(file = "image8.jpeg")
w2 = Label(user_defined,image = photo2)
w2.pack()

present_time=Frame(window)
present_time.grid(row=0, column=0, sticky='news')
photo3 = ImageTk.PhotoImage(file = "image11.jpg")
w3 = Label(present_time,image = photo3)
w3.pack()

western_stall=Frame(window)
western_stall.grid(row=0, column=0, sticky='news')
photo4 = ImageTk.PhotoImage(file = "image12.jpg")
w4 = Label(western_stall,image = photo4)
w4.pack()

korean_stall=Frame(window)
korean_stall.grid(row=0, column=0, sticky="news")
photo5 = ImageTk.PhotoImage(file = "image12.jpg")
w5 = Label(korean_stall,image = photo5)
w5.pack()

japanese_stall=Frame(window)
japanese_stall.grid(row=0, column=0, sticky='news')
photo6 = ImageTk.PhotoImage(file = "image12.jpg")
w6 = Label(japanese_stall,image = photo6)
w6.pack()

MCD=Frame(window)
MCD.grid(row=0, column=0, sticky='news')
photo7 = ImageTk.PhotoImage(file = "image12.jpg")
w7 = Label(MCD,image = photo7)
w7.pack()

KFC=Frame(window)
KFC.grid(row=0, column=0, sticky='news')
photo8 = ImageTk.PhotoImage(file = "image12.jpg")
w8 = Label(KFC,image = photo8)
w8.pack()

top = Frame(window)
top.grid(row=0, column=0, sticky='news')
photo9 = ImageTk.PhotoImage(file = "image11.jpg")
w9 = Label(top,image = photo9)
w9.pack()

calendar = Frame(window)
calendar.grid(row=0, column=0, sticky='news')
photo10 = ImageTk.PhotoImage(file = "image8.jpeg")
w10 = Label(user_defined,image = photo10)
w10.pack()

toplevel1 = Frame(window)
toplevel1.grid(row=0, column=0, sticky='news')
photo11 = ImageTk.PhotoImage(file = "image8.jpeg")
w11 = Label(toplevel1,image = photo11)
w11.pack()

toplevel2 = Frame(window)
toplevel2.grid(row=0, column=0, sticky='news')
photo12 = ImageTk.PhotoImage(file = "image11.jpg")
w12 = Label(toplevel2,image = photo12)
w12.pack()

western_stall1=Frame(window)
western_stall1.grid(row=0, column=0, sticky='news')
photo13 = ImageTk.PhotoImage(file = "image12.jpg")
w13 = Label(western_stall1,image = photo13)
w13.pack()

western_stall2=Frame(window)
western_stall2.grid(row=0, column=0, sticky='news')
photo14 = ImageTk.PhotoImage(file = "image12.jpg")
w14 = Label(western_stall2,image = photo14)
w14.pack()

western_stall3=Frame(window)
western_stall3.grid(row=0, column=0, sticky='news')
photo15 = ImageTk.PhotoImage(file = "image12.jpg")
w15 = Label(western_stall3,image = photo15)
w15.pack()

korean_stall1=Frame(window)
korean_stall1.grid(row=0, column=0, sticky='news')
photo16 = ImageTk.PhotoImage(file = "image12.jpg")
w16 = Label(korean_stall1,image = photo16)
w16.pack()

korean_stall2 = Frame(window)
korean_stall2.grid(row=0,column=0,sticky='news')
photo17 = ImageTk.PhotoImage(file = "image12.jpg")
w17 = Label(korean_stall2,image = photo17)
w17.pack()

korean_stall3=Frame(window)
korean_stall3.grid(row=0, column=0, sticky='news')
photo18 = ImageTk.PhotoImage(file = "image12.jpg")
w18 = Label(korean_stall3,image = photo18)
w18.pack()

japanese_stall1=Frame(window)
japanese_stall1.grid(row=0, column=0, sticky='news')
photo19 = ImageTk.PhotoImage(file = "image12.jpg")
w19 = Label(japanese_stall1,image = photo19)
w19.pack()

japanese_stall2=Frame(window)
japanese_stall2.grid(row=0, column=0, sticky='news')
photo20 = ImageTk.PhotoImage(file = "image12.jpg")
w20 = Label(japanese_stall2,image = photo20)
w20.pack()

japanese_stall3=Frame(window)
japanese_stall3.grid(row=0, column=0, sticky='news')
photo21 = ImageTk.PhotoImage(file = "image12.jpg")
w21 = Label(japanese_stall3,image = photo21)
w21.pack()

MCD1=Frame(window)
MCD1.grid(row=0, column=0, sticky='news')
photo22 = ImageTk.PhotoImage(file = "image12.jpg")
w22 = Label(MCD1,image = photo22)
w22.pack()

MCD2=Frame(window)
MCD2.grid(row=0, column=0, sticky='news')
photo23 = ImageTk.PhotoImage(file = "image12.jpg")
w23 = Label(MCD2,image = photo23)
w23.pack()

MCD3=Frame(window)
MCD3.grid(row=0, column=0, sticky='news')
photo24 = ImageTk.PhotoImage(file = "image12.jpg")
w24 = Label(MCD3,image = photo24)
w24.pack()

KFC1=Frame(window)
KFC1.grid(row=0, column=0, sticky='news')
photo25 = ImageTk.PhotoImage(file = "image12.jpg")
w25 = Label(KFC1,image = photo25)
w25.pack()

KFC2=Frame(window)
KFC2.grid(row=0, column=0, sticky='news')
photo26 = ImageTk.PhotoImage(file = "image12.jpg")
w26 = Label(KFC2,image = photo26)
w26.pack()

KFC3=Frame(window)
KFC3.grid(row=0, column=0, sticky='news')
photo27 = ImageTk.PhotoImage(file = "image12.jpg")
w27 = Label(KFC3,image = photo27)
w27.pack()
mainframe.tkraise()
#==========================================define labels and buttons========================#ABHISHEK===========================

label1 = Label(mainframe,text="Welcome to North spine food court",fg="black",bg="white",font=("arial",30),relief="solid")
label1.place(x=12,y=50)
button1 = Button(mainframe,text="user defined time",font=("arial",25),fg="black",bg="yellow",relief="raised",command = lambda:user_defined.tkraise())
button1.place(x=285,y=255)
button2 = Button(mainframe,text="current time",font=("arial",25),fg="black",bg="yellow",relief="raised",command = lambda:present_time.tkraise())
button2.place(x=310,y=480)
button01 = Button(mainframe,text="exit",font=("arial",20),command=lambda:exit1())
button01.place(x=362,y=650)
#==========================================================================================================================

#to exit the program
def exit1():                                                  #ABHISHEK
    exit()

#try and except function for the entry given by the user
def ABT(s):                                                   #ABHISHEK
    try:
        s = int(s)
        if 50>= int(s) >= 0:
            s = int(s) * 2
            tkinter.messagebox.showinfo("the waiting time in minutes is: ",s)
        else:
            raise ValueError
    except ValueError:
        tkinter.messagebox.showinfo("invalid input", "please enter the correct number of people standing in queue")

#function for the western stall
def abc1():                                                   #ABHISHEK
    western_stall.tkraise()
    if 9<=int(current_time)<11:
        label3=Label(western_stall,text=western_food_breakfast[current_day][0],font="arial")
        label3.place(x=140,y=200)
        label3=Label(western_stall,text=western_food_breakfast[current_day][1],font="arial")
        label3.place(x=140,y=250)
        fn = IntVar()
        entry01 = Entry(western_stall,textvariable=fn)
        fn.set(0)
        entry01.place(x=140,y=400)
        label = Label(western_stall,text="enter number of people before you")
        label.place(x=130,y=430)
        button17 = Button(western_stall,text="calculate",command=lambda:ABT(entry01.get()))
        button17.place(x=200,y=470)
        button7=Button(western_stall,text="back",command= lambda: present_time.tkraise())
        button7.place(x=210,y=550)
    elif 11<=int(current_time)<=20:
        label4=Label(western_stall,text=western_food_days[current_day][0],font="arial")
        label4.place(x=140,y=170)
        label5=Label(western_stall,text=western_food_days[current_day][1],font="arial")
        label5.place(x=140,y=230)
        label4=Label(western_stall,text=western_food_days[current_day][2],font="arial")
        label4.place(x=140,y=290)
        label4=Label(western_stall,text=western_food_days[current_day][3],font="arial")
        label4.place(x=140,y=350)
        fn = IntVar()
        entry01 = Entry(western_stall,textvariable=fn)
        fn.set(0)
        entry01.place(x=140,y=400)
        label = Label(western_stall,text="enter number of people before you")
        label.place(x=130,y=430)
        button17 = Button(western_stall,text="calculate",command=lambda:ABT(entry01.get()))
        button17.place(x=200,y=470)
        button8=Button(western_stall,text="back",command= lambda: present_time.tkraise())
        button8.place(x=210,y=550)
    else:
        tkinter.messagebox.showinfo("message","the shop is closed")
        button9=Button(western_stall,text="back",command=lambda:present_time.tkraise())
        button9.place(x=210,y=375)

#function for the korean stall
def abc2():                                                   #ABHISHEK
    korean_stall.tkraise()
    if 9<=int(current_time)<11:
        label3=Label(korean_stall,text=korean_food_breakfast[current_day][0],font="arial")
        label3.place(x=140,y=200)
        label3=Label(korean_stall,text=korean_food_breakfast[current_day][1],font="arial")
        label3.place(x=140,y=250)
        fn = IntVar()
        entry01 = Entry(korean_stall,textvariable=fn)
        fn.set(0)
        entry01.place(x=140,y=400)
        label = Label(korean_stall,text="enter number of people before you")
        label.place(x=130,y=430)
        button17 = Button(korean_stall,text="calculate",command=lambda:ABT(entry01.get()))
        button17.place(x=200,y=470)
        button7=Button(korean_stall,text="back",command= lambda: present_time.tkraise())
        button7.place(x=210,y=550)
    elif 11<=int(current_time)<=20:
        label4=Label(korean_stall,text=korean_food_days[current_day][0],font="arial")
        label4.place(x=140,y=170)
        label5=Label(korean_stall,text=korean_food_days[current_day][1],font="arial")
        label5.place(x=140,y=230)
        label4=Label(korean_stall,text=korean_food_days[current_day][2],font="arial")
        label4.place(x=140,y=290)
        label4=Label(korean_stall,text=korean_food_days[current_day][3],font="arial")
        label4.place(x=140,y=350)
        fn = IntVar()
        entry01 = Entry(korean_stall,textvariable=fn)
        fn.set(0)
        entry01.place(x=140,y=400)
        label = Label(korean_stall,text="enter number of people before you")
        label.place(x=130,y=430)
        button17 = Button(korean_stall,text="calculate",command=lambda:ABT(entry01.get()))
        button17.place(x=200,y=470)
        button8=Button(korean_stall,text="back",command= lambda: present_time.tkraise())
        button8.place(x=210,y=550)
    else:
        tkinter.messagebox.showinfo("message","the shop is closed")
        button9=Button(korean_stall,text="back",command=lambda:present_time.tkraise())
        button9.place(x=210,y=375)

#function for the MCD stall
def abc3():                                                   #ABHISHEK
    MCD.tkraise()
    if 9<=int(current_time)<11:
        label3=Label(MCD,text=macdonalds_breakfast[current_day][0],font="arial")
        label3.place(x=140,y=200)
        label3=Label(MCD,text=macdonalds_breakfast[current_day][1],font="arial")
        label3.place(x=140,y=250)
        fn = IntVar()
        entry01 = Entry(MCD,textvariable=fn)
        fn.set(0)
        entry01.place(x=140,y=400)
        label = Label(MCD,text="enter number of people before you")
        label.place(x=130,y=430)
        button17 = Button(MCD,text="calculate",command=lambda:ABT(entry01.get()))
        button17.place(x=200,y=470)
        button7=Button(MCD,text="back",command= lambda: present_time.tkraise())
        button7.place(x=210,y=550)
    elif 11<=int(current_time)<=22:
        label4=Label(MCD,text=macdonalds_food_days[current_day][0],font="arial")
        label4.place(x=140,y=170)
        label5=Label(MCD,text=macdonalds_food_days[current_day][1],font="arial")
        label5.place(x=140,y=230)
        label4=Label(MCD,text=macdonalds_food_days[current_day][2],font="arial")
        label4.place(x=140,y=290)
        label4=Label(MCD,text=macdonalds_food_days[current_day][3],font="arial")
        label4.place(x=140,y=350)
        fn = IntVar()
        entry01 = Entry(MCD,textvariable=fn)
        fn.set(0)
        entry01.place(x=140,y=400)
        label = Label(MCD,text="enter number of people before you")
        label.place(x=130,y=430)
        button17 = Button(MCD,text="calculate",command=lambda:ABT(entry01.get()))
        button17.place(x=200,y=470)
        button8=Button(MCD,text="back",command= lambda: present_time.tkraise())
        button8.place(x=210,y=550)
    else:
        tkinter.messagebox.showinfo("message","the shop is closed")
        button9=Button(MCD,text="back",command=lambda:present_time.tkraise())
        button9.place(x=210,y=375)

#function for the japanese stall
def abc4():                                                   #ABHISHEK
    japanese_stall.tkraise()
    if 9<=int(current_time)<11:
        label3=Label(japanese_stall,text=japanese_food_breakfast[current_day][0],font="arial")
        label3.place(x=140,y=200)
        label3=Label(japanese_stall,text=japanese_food_breakfast[current_day][1],font="arial")
        label3.place(x=140,y=250)
        fn = IntVar()
        entry01 = Entry(japanese_stall,textvariable=fn)
        fn.set(0)
        entry01.place(x=140,y=400)
        label = Label(japanese_stall,text="enter number of people before you")
        label.place(x=130,y=430)
        button17 = Button(japanese_stall,text="calculate",command=lambda:ABT(entry01.get()))
        button17.place(x=200,y=470)
        button7=Button(japanese_stall,text="back",command= lambda: present_time.tkraise())
        button7.place(x=210,y=550)
    elif 11<=int(current_time)<=20:
        label4=Label(japanese_stall,text=japanese_food_days[current_day][0],font="arial")
        label4.place(x=140,y=170)
        label5=Label(japanese_stall,text=japanese_food_days[current_day][1],font="arial")
        label5.place(x=140,y=230)
        label4=Label(japanese_stall,text=japanese_food_days[current_day][2],font="arial")
        label4.place(x=140,y=290)
        label4=Label(japanese_stall,text=japanese_food_days[current_day][3],font="arial")
        label4.place(x=140,y=350)
        fn = IntVar()
        entry01 = Entry(japanese_stall,textvariable=fn)
        fn.set(0)
        entry01.place(x=140,y=400)
        label = Label(japanese_stall,text="enter number of people before you")
        label.place(x=130,y=430)
        button17 = Button(japanese_stall,text="calculate",command=lambda:ABT(entry01.get()))
        button17.place(x=200,y=470)
        button8=Button(japanese_stall,text="back",command= lambda: present_time.tkraise())
        button8.place(x=210,y=550)
    else:
        tkinter.messagebox.showinfo("message","the shop is closed")
        button9=Button(japanese_stall,text="back",command=lambda:present_time.tkraise())
        button9.place(x=205,y=375)

#function for the KFC stall
def abc5():                                                   #ABHISHEK
    KFC.tkraise()
    if 9<=int(current_time)<11:
        label3=Label(KFC,text=KFC_food_breakfast[current_day][0],font="arial")
        label3.place(x=140,y=200)
        label3=Label(KFC,text=KFC_food_breakfast[current_day][1],font="arial")
        label3.place(x=140,y=250)
        fn = IntVar()
        entry01 = Entry(KFC,textvariable=fn)
        fn.set(0)
        entry01.place(x=140,y=400)
        label = Label(KFC,text="enter number of people before you")
        label.place(x=130,y=430)
        button17 = Button(KFC,text="calculate",command=lambda:ABT(entry01.get()))
        button17.place(x=200,y=470)
        button7=Button(KFC,text="back",command= lambda: present_time.tkraise())
        button7.place(x=210,y=550)
    elif 11<=int(current_time)<=22:
        label4=Label(KFC,text=KFC_food_days[current_day][0],font="arial")
        label4.place(x=140,y=170)
        label5=Label(KFC,text=KFC_food_days[current_day][1],font="arial")
        label5.place(x=140,y=230)
        label4=Label(KFC,text=KFC_food_days[current_day][2],font="arial")
        label4.place(x=140,y=290)
        label4=Label(KFC,text=KFC_food_days[current_day][3],font="arial")
        label4.place(x=140,y=350)
        fn = IntVar()
        entry01 = Entry(KFC,textvariable=fn)
        fn.set(0)
        entry01.place(x=140,y=400)
        label = Label(KFC,text="enter number of people before you")
        label.place(x=130,y=430)
        button17 = Button(KFC,text="calculate",command=lambda:ABT(entry01.get()))
        button17.place(x=200,y=470)
        button8=Button(KFC,text="back",command= lambda: present_time.tkraise())
        button8.place(x=210,y=550)
    else:
        tkinter.messagebox.showinfo("message","the shop is closed")
        button9=Button(KFC,text="back",command=lambda:present_time.tkraise())
        button9.place(x=205,y=375)

    
#=====================================stall buttons to view the food menus========================#ABHISHEK====================
label2 = Label(present_time,text=current_day,font=("arial",30),relief="solid")
label2.place(x=190,y=80)
button1 = Button(present_time,text="western stall",fg="black",bg="black",font=("arial",20),command = lambda:abc1())
button1.place(x=195,y=240)
button2 = Button(present_time,text="korean stall",fg="black",bg="black",font=("arial",20),command = lambda:abc2())
button2.place(x=197,y=280)
button3 = Button(present_time,text="japanese stall",fg="black",font=("arial",20),bg="black",command = lambda:abc4())
button3.place(x=185,y=320)
button4 = Button(present_time,text="MCD",fg="black",bg="black",font=("arial",20),command = lambda:abc3())
button4.place(x=220,y=360)
button5 = Button(present_time,text="KFC",fg="black",bg="black",font=("arial",20),command = lambda:abc5())
button5.place(x=222,y=400)
button6 = Button(present_time,text="back",font=("arial"),command = lambda:mainframe.tkraise())
button6.place(x=225,y=580)
label01 = Label(present_time,text="Stalls open at 9 AM and close at 8 PM")
label01.place(x=125,y=630)
label02 = Label(present_time,text="MCD and KFC open at 9 AM and close at 10 PM ")
label02.place(x=100,y=650)

button7 = Button(user_defined,text="back",font=("arial",20),command=lambda:mainframe.tkraise())
button7.place(x=225,y=500)
#==============================================================================================================================

# =================================display the calendar for the user to select the time=================#ABHISHEK=============         
def cal_fun():
    top.tkraise()
    cal = Calendar(top,font = "Arial",selectmode="day",year=2019,month=11,day=13)
    cal.place(x=110,y=180)
    # return the value of the date that the user selects
    def cal_val():                                                                                      #ABHISHEK
        #used to chnage to datetime object and get the day number of the weeek (Monday=0)
        datetime_object= parser.parse(cal.get_date())
        x = datetime_object.weekday()
        
        toplevel1.tkraise()
        # using the list in order to get the food menu for each stall depending on the day number of the week
        weekdays_list=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
        label1 = Label(toplevel1,text="hours",font=("arial",20))
        label1.place(x=185,y=200)
        label2 = Label(toplevel1,text="minutes",font=("arial",20))
        label2.place(x=185,y=250)
        OPTIONS1 = list(range(1,25))  # creates an option menu 
        OPTIONS2 = [0,15,30,45]       # creates an option menu  
        variable1 = StringVar(toplevel1)
        variable1.set(OPTIONS1[9])     #sets default value of the options menu
        w1 = OptionMenu(toplevel1, variable1, *OPTIONS1)
        w1.config(font=("arial",20))
        w1.place(x=270,y=200)
        variable2 = StringVar(toplevel1)
        variable2.set(OPTIONS2[2])      #sets default value of the options menu   
        w2 = OptionMenu(toplevel1, variable2, *OPTIONS2)
        w2.config(font=("arial",20))
        w2.place(x=270,y=250)
        button14 = Button(toplevel1,text="next page",font=("arial",20),command = lambda:toplevel2.tkraise())
        button14.place(x=207,y=400)
        button11 = Button(toplevel1,text="back",font=("arial",20),command = lambda:top.tkraise())
        button11.place(x=225,y=470)

        # function for getiing the food menu for western stall depending upon the user defined data and time
        def cba1():                                                                      #WEN XIU
            if  8<=int(variable1.get())<=11:
                western_stall1.tkraise()
                label6 = Label(western_stall1,text=western_food_breakfast[weekdays_list[x]][0])
                label6.place(x=140,y=200)
                label7 = Label(western_stall1,text=western_food_breakfast[weekdays_list[x]][1])
                label7.place(x=140,y=250)
                button15 = Button(western_stall1,text="back",font=("arial"),command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=550)
                fn = IntVar()
                entry01 = Entry(western_stall1,textvariable=fn)
                fn.set(0)
                entry01.place(x=140,y=400)
                label = Label(western_stall1,text="enter number of people before you")
                label.place(x=130,y=430)
                button17 = Button(western_stall1,text="calculate",command=lambda:ABT(entry01.get()))
                button17.place(x=200,y=470)
            elif 11<int(variable1.get())<=23:
                western_stall2.tkraise()
                label8 = Label(western_stall2,text=western_food_days[weekdays_list[x]][0])
                label8.place(x=140,y=200)
                label9 = Label(western_stall2,text=western_food_days[weekdays_list[x]][1])
                label9.place(x=140,y=250)
                label10 = Label(western_stall2,text=western_food_days[weekdays_list[x]][2])
                label10.place(x=140,y=300)
                label11 = Label(western_stall2,text=western_food_days[weekdays_list[x]][3])
                label11.place(x=140,y=350)
                button15 = Button(western_stall2,text="back",font=("arial"),command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=550)
                fn = IntVar()
                entry01 = Entry(western_stall2,textvariable=fn)
                entry01.place(x=140,y=400)
                label = Label(western_stall2,text="enter number of people before you")
                label.place(x=130,y=430)
                button17 = Button(western_stall2,text="calculate",command=lambda:ABT(entry01.get()))
                button17.place(x=200,y=470)
            else :
                western_stall3.tkraise()
                label6 = Label(western_stall3,text="shop closed")
                label6.place(x=195,y=200)
                button15 = Button(western_stall3,text="back",font=("arial"),command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=400)

        # function for getiing the food menu for korean stall depending upon the user defined data and time 
        def cba2():                                                                      #WEN XIU
            if  8<=int(variable1.get())<=11:
                korean_stall1.tkraise()
                label6 = Label(korean_stall1,text=korean_food_breakfast[weekdays_list[x]][0])
                label6.place(x=140,y=200)
                label7 = Label(korean_stall1,text=korean_food_breakfast[weekdays_list[x]][1])
                label7.place(x=140,y=250)
                button15 = Button(korean_stall1,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=550)
                fn = IntVar()
                entry01 = Entry(korean_stall1,textvariable=fn)
                entry01.place(x=140,y=400)
                label = Label(korean_stall1,text="enter number of people before you")
                label.place(x=130,y=430)
                button17 = Button(korean_stall1,text="calculate",command=lambda:ABT(entry01.get()))
                button17.place(x=200,y=470)
            elif 11<int(variable1.get())<=20:
                korean_stall2.tkraise()
                label8 = Label(korean_stall2,text=korean_food_days[weekdays_list[x]][0])
                label8.place(x=140,y=200)
                label9 = Label(korean_stall2,text=korean_food_days[weekdays_list[x]][1])
                label9.place(x=140,y=250)
                label10 = Label(korean_stall2,text=korean_food_days[weekdays_list[x]][2])
                label10.place(x=140,y=300)
                label11 = Label(korean_stall2,text=korean_food_days[weekdays_list[x]][3])
                label11.place(x=140,y=350)
                button15 = Button(korean_stall2,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=550)
                fn = IntVar()
                entry01 = Entry(korean_stall2,textvariable=fn)
                entry01.place(x=140,y=400)
                label = Label(korean_stall2,text="enter number of people before you")
                label.place(x=130,y=430)
                button17 = Button(korean_stall2,text="calculate",command=lambda:ABT(entry01.get()))
                button17.place(x=200,y=470)
            else :
                korean_stall3.tkraise()
                label6 = Label(korean_stall3,text="shop closed")
                label6.place(x=195,y=200)
                button15 = Button(korean_stall3,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=400)

        # function for getiing the food menu for japanese stall depending upon the user defined data and time
        def cba3():                                                                      #WEN XIU
            if  8<=int(variable1.get())<=11:
                japanese_stall1.tkraise()
                label6 = Label(japanese_stall1,text=japanese_food_breakfast[weekdays_list[x]][0])
                label6.place(x=140,y=200)
                label7 = Label(japanese_stall1,text=japanese_food_breakfast[weekdays_list[x]][1])
                label7.place(x=140,y=250)
                button15 = Button(japanese_stall1,text="back",font=("arial"),command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=550)
                fn = IntVar()
                entry01 = Entry(japanese_stall1,textvariable=fn)
                entry01.place(x=140,y=400)
                label = Label(japanese_stall1,text="enter number of people before you")
                label.place(x=130,y=430)
                button17 = Button(japanese_stall1,text="calculate",command=lambda:ABT(entry01.get()))
                button17.place(x=200,y=470)
            elif 11<int(variable1.get())<=20:
                japanese_stall2.tkraise()
                label8 = Label(japanese_stall2,text=japanese_food_days[weekdays_list[x]][0])
                label8.place(x=140,y=200)
                label9 = Label(japanese_stall2,text=japanese_food_days[weekdays_list[x]][1])
                label9.place(x=140,y=250)
                label10 = Label(japanese_stall2,text=japanese_food_days[weekdays_list[x]][2])
                label10.place(x=140,y=300)
                label11 = Label(japanese_stall2,text=japanese_food_days[weekdays_list[x]][3])
                label11.place(x=140,y=350)
                button15 = Button(japanese_stall2,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=550)
                fn = IntVar()
                entry01 = Entry(japanese_stall2,textvariable=fn)
                entry01.place(x=140,y=400)
                label = Label(japanese_stall2,text="enter number of people before you")
                label.place(x=130,y=430)
                button17 = Button(japanese_stall2,text="calculate",command=lambda:ABT(entry01.get()))
                button17.place(x=200,y=470)
            else :
                japanese_stall3.tkraise()
                label6 = Label(japanese_stall3,text="shop closed")
                label6.place(x=195,y=200)
                button15 = Button(japanese_stall3,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=400)

        # function for getiing the food menu for MCD depending upon the user defined data and time
        def cba4():                                                                      #WEN XIU
            if  8<=int(variable1.get())<=11:
                MCD1.tkraise()
                label6 = Label(MCD1,text=macdonalds_breakfast[weekdays_list[x]][0])
                label6.place(x=140,y=200)
                label7 = Label(MCD1,text=macdonalds_breakfast[weekdays_list[x]][1])
                label7.place(x=140,y=250)
                button15 = Button(MCD1,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=550)
                fn = IntVar()
                entry01 = Entry(MCD1,textvariable=fn)
                entry01.place(x=140,y=400)
                label = Label(MCD1,text="enter number of people before you")
                label.place(x=130,y=430)
                button17 = Button(MCD1,text="calculate",command=lambda:ABT(entry01.get()))
                button17.place(x=200,y=470)
            elif 11<int(variable1.get())<=22:
                MCD2.tkraise()
                label8 = Label(MCD2,text=macdonalds_food_days[weekdays_list[x]][0])
                label8.place(x=140,y=200)
                label9 = Label(MCD2,text=macdonalds_food_days[weekdays_list[x]][1])
                label9.place(x=140,y=250)
                label10 = Label(MCD2,text=macdonalds_food_days[weekdays_list[x]][2])
                label10.place(x=140,y=300)
                label11 = Label(MCD2,text=macdonalds_food_days[weekdays_list[x]][3])
                label11.place(x=140,y=350)
                button15 = Button(MCD2,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=550)
                fn = IntVar()
                entry01 = Entry(MCD2,textvariable=fn)
                entry01.place(x=140,y=400)
                label = Label(MCD2,text="enter number of people before you")
                label.place(x=130,y=430)
                button17 = Button(MCD2,text="calculate",command=lambda:ABT(entry01.get()))
                button17.place(x=200,y=470)
            else :
                MCD3.tkraise()
                label6 = Label(MCD3,text="shop closed")
                label6.place(x=195,y=200)
                button15 = Button(MCD3,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=400)

        # function for getiing the food menu for KFC depending upon the user defined data and time
        def cba5():                                                                      #WEN XIU
            if  8<=int(variable1.get())<=11:
                KFC1.tkraise()
                label6 = Label(KFC1,text=KFC_food_breakfast[weekdays_list[x]][0])
                label6.place(x=140,y=200)
                label7 = Label(KFC1,text=KFC_food_breakfast[weekdays_list[x]][1])
                label7.place(x=140,y=250)
                button15 = Button(KFC1,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=550)
                fn = IntVar()
                entry01 = Entry(KFC1,textvariable=fn)
                entry01.place(x=140,y=400)
                label = Label(KFC1,text="enter number of people before you")
                label.place(x=130,y=430)
                button17 = Button(KFC1,text="calculate",command=lambda:ABT(entry01.get()))
                button17.place(x=200,y=470)
            elif 11<int(variable1.get())<=22:
                KFC2.tkraise()
                label8 = Label(KFC2,text=KFC_food_days[weekdays_list[x]][0])
                label8.place(x=140,y=200)
                label9 = Label(KFC2,text=KFC_food_days[weekdays_list[x]][1])
                label9.place(x=140,y=250)
                label10 = Label(KFC2,text=KFC_food_days[weekdays_list[x]][2])
                label10.place(x=140,y=300)
                label11 = Label(KFC2,text=KFC_food_days[weekdays_list[x]][3])
                label11.place(x=140,y=350)
                button15 = Button(KFC2,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=550)
                fn = IntVar()
                entry01 = Entry(KFC2,textvariable=fn)
                entry01.place(x=140,y=400)
                label = Label(KFC2,text="enter number of people before you")
                label.place(x=130,y=430)
                button17 = Button(KFC2,text="calculate",command=lambda:ABT(entry01.get()))
                button17.place(x=200,y=470)
            else :
                KFC3.tkraise()
                label6 = Label(KFC3,text="shop closed")
                label6.place(x=195,y=200)
                button15 = Button(KFC3,text="back",command=lambda:toplevel2.tkraise())
                button15.place(x=210,y=400)

      
        # the buttons used to get the menus of the stalls 
        button16 = Button(toplevel2,text="western stall",font=("arial",20),command=lambda:cba1())
        button16.place(x=195,y=200)
        button16 = Button(toplevel2,text="korean stall",font=("arial",20),command=lambda:cba2())
        button16.place(x=200,y=240)
        button16 = Button(toplevel2,text="japanese stall",font=("arial",20),command=lambda:cba3())
        button16.place(x=187,y=280)
        button16 = Button(toplevel2,text="MCD",font=("arial",20),command=lambda:cba4())
        button16.place(x=225,y=320)
        button16 = Button(toplevel2,text="KFC",font=("arial",20),command=lambda:cba5())
        button16.place(x=226,y=360)
        button11 = Button(toplevel2,text="back",font=("arial",20),command = lambda:toplevel1.tkraise())
        button11.place(x=225,y=500)
        label01 = Label(toplevel2,text="Stalls open at 9 AM and close at 8 PM")
        label01.place(x=125,y=630)
        label02 = Label(toplevel2,text="MCD and KFC open at 9 AM and close at 10 PM ")
        label02.place(x=100,y=650)
                
    button8 = Button(top,text="next page",font=("arial",20),command=lambda: cal_val())
    button8.place(x=207,y=400)
    button14 = Button(top,text="back",font=("arial",20),command=lambda:user_defined.tkraise())
    button14.place(x=225,y=470)                      
        
button8 = Button(user_defined,text="select date and time ",font=("arial",40),bg="yellow",relief = "raised",command=lambda:cal_fun())
button8.place(x=70,y=300)

#the window should be closed in order to execute the frames and the buttons and labels
window.mainloop()


